[build]
  command = "npm run build"
  functions = "functions-build"
  publish = "build"
  base = "CryptoKnight"

[dev]
  command = "npm run start"
  functions = "functions"
  publish = "build"
  targetPort = 3001

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
