[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "build"
  environment = { NODE_ENV = 'production' }

[dev]
  command = "npm run start"
  functions = "netlify/functions"
  publish = "build"
  targetPort = 3001

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
